---
# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-mysql
  namespace: default
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-8.8.12
    app.kubernetes.io/instance: test-mysql
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mysql-root-password: "ZTR6Ym1rRFNpRQ=="
  mysql-password: "SGxJcWtzekloaA=="
