---
# Source: mysql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-mysql
  namespace: default
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-8.8.12
    app.kubernetes.io/instance: test-mysql
    app.kubernetes.io/managed-by: Helm
  annotations:
secrets:
  - name: test-mysql
